name: Update Users Data

on:
  # This allows the "ping" from your website to start the action
  workflow_dispatch:
    inputs:
      userData:
        description: 'JSON string of user data'
        required: true

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Change 20 to 24 to stay ahead of the deprecation
          node-version: 24

      - name: Run Update Script
        run: node update.js '${{ github.event.inputs.userData }}'

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add users.json
          git commit -m "Add new user data"
          git push
